package org.galsang.admin.base.dao;

import org.galsang.admin.base.model.AuthDept;

public interface AuthDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insert(AuthDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insertSelective(AuthDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    AuthDept selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKeySelective(AuthDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_dept
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKey(AuthDept record);
}