package org.galsang.admin.base.dao;

import org.galsang.admin.base.model.AuthUser;

import java.util.List;

public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    AuthUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKey(AuthUser record);


    /**
     *
     * @param username
     * @return
     */
    AuthUser selectByUserName(String username);


    /**
     * 查询所用用户
     * @return
     */
    List<AuthUser> selectAll();


}