package org.galsang.admin.base.dao;

import org.galsang.admin.base.model.AuthRole;

public interface AuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insert(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insertSelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    AuthRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKeySelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKey(AuthRole record);
}