package org.galsang.admin.base.dao;

import org.galsang.admin.base.model.AuthMenu;

public interface AuthMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insert(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insertSelective(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    AuthMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKeySelective(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKey(AuthMenu record);
}