package org.galsang.admin.base.dao;

import org.galsang.admin.base.model.AuthAuthority;

public interface AuthAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insert(AuthAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int insertSelective(AuthAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    AuthAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKeySelective(AuthAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    int updateByPrimaryKey(AuthAuthority record);
}