package org.galsang.admin.base.model;

import java.io.Serializable;
import java.util.Date;

public class AuthAuthority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.roleId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.menuId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.id
     *
     * @return the value of auth_authority.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.id
     *
     * @param id the value for auth_authority.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.roleId
     *
     * @return the value of auth_authority.roleId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.roleId
     *
     * @param roleId the value for auth_authority.roleId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.menuId
     *
     * @return the value of auth_authority.menuId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.menuId
     *
     * @param menuId the value for auth_authority.menuId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.deleted
     *
     * @return the value of auth_authority.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.deleted
     *
     * @param deleted the value for auth_authority.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.remark
     *
     * @return the value of auth_authority.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.remark
     *
     * @param remark the value for auth_authority.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.createdTime
     *
     * @return the value of auth_authority.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.createdTime
     *
     * @param createdTime the value for auth_authority.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.updatedTime
     *
     * @return the value of auth_authority.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.updatedTime
     *
     * @param updatedTime the value for auth_authority.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthAuthority other = (AuthAuthority) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", menuId=").append(menuId);
        sb.append(", deleted=").append(deleted);
        sb.append(", remark=").append(remark);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}