package org.galsang.admin.base.model;

import java.io.Serializable;
import java.util.Date;

public class AuthMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.code
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.name
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.type
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.url
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.icon
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.levelCode
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String levelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.parentId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.orderNum
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_menu.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.id
     *
     * @return the value of auth_menu.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.id
     *
     * @param id the value for auth_menu.id
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.code
     *
     * @return the value of auth_menu.code
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.code
     *
     * @param code the value for auth_menu.code
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.name
     *
     * @return the value of auth_menu.name
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.name
     *
     * @param name the value for auth_menu.name
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.type
     *
     * @return the value of auth_menu.type
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.type
     *
     * @param type the value for auth_menu.type
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.url
     *
     * @return the value of auth_menu.url
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.url
     *
     * @param url the value for auth_menu.url
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.icon
     *
     * @return the value of auth_menu.icon
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.icon
     *
     * @param icon the value for auth_menu.icon
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.levelCode
     *
     * @return the value of auth_menu.levelCode
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.levelCode
     *
     * @param levelCode the value for auth_menu.levelCode
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode == null ? null : levelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.parentId
     *
     * @return the value of auth_menu.parentId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.parentId
     *
     * @param parentId the value for auth_menu.parentId
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.orderNum
     *
     * @return the value of auth_menu.orderNum
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.orderNum
     *
     * @param orderNum the value for auth_menu.orderNum
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.deleted
     *
     * @return the value of auth_menu.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.deleted
     *
     * @param deleted the value for auth_menu.deleted
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.remark
     *
     * @return the value of auth_menu.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.remark
     *
     * @param remark the value for auth_menu.remark
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.createdTime
     *
     * @return the value of auth_menu.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.createdTime
     *
     * @param createdTime the value for auth_menu.createdTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_menu.updatedTime
     *
     * @return the value of auth_menu.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_menu.updatedTime
     *
     * @param updatedTime the value for auth_menu.updatedTime
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AuthMenu other = (AuthMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getLevelCode() == null ? other.getLevelCode() == null : this.getLevelCode().equals(other.getLevelCode()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getLevelCode() == null) ? 0 : getLevelCode().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated Thu Dec 21 11:56:56 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", url=").append(url);
        sb.append(", icon=").append(icon);
        sb.append(", levelCode=").append(levelCode);
        sb.append(", parentId=").append(parentId);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", deleted=").append(deleted);
        sb.append(", remark=").append(remark);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}